const darkTheme = {
    'code[class*="language-"]': {
        color: "#f8f8f2",
        background: "none",
        textAlign: "left",
        whiteSpace: "pre",
        wordSpacing: "normal",
        wordBreak: "normal",
        wordWrap: "normal",
        lineHeight: "1.5",
        tabSize: "2",
        hyphens: "none",
    },
    'pre[class*="language-"]': {
        color: "#f8f8f2",
        background: "none",
        textAlign: "left",
        whiteSpace: "pre",
        wordSpacing: "normal",
        wordBreak: "normal",
        wordWrap: "normal",
        lineHeight: "1.5",
        tabSize: "2",
        hyphens: "none",
        padding: "1em",
        margin: "0",
        overflow: "auto",
        borderRadius: "0.3em",
    },
    ':not(pre) > code[class*="language-"]': {
        background: "none",
        padding: ".1em",
        borderRadius: ".3em",
        whiteSpace: "normal",
    },
    comment: {color: "#6272a4"},
    prolog: {color: "#6272a4"},
    doctype: {color: "#6272a4"},
    cdata: {color: "#6272a4"},
    punctuation: {color: "#f8f8f2"},
    property: {color: "#ff79c6"},
    tag: {color: "#ff79c6"},
    constant: {color: "#bd93f9"},
    symbol: {color: "#bd93f9"},
    deleted: {color: "#bd93f9"},
    boolean: {color: "#bd93f9"},
    number: {color: "#bd93f9"},
    selector: {color: "#50fa7b"},
    "attr-name": {color: "#50fa7b"},
    string: {color: "#f1fa8c"},
    char: {color: "#f1fa8c"},
    builtin: {color: "#f1fa8c"},
    inserted: {color: "#f1fa8c"},
    operator: {color: "#ff79c6"},
    entity: {color: "#f8f8f2", cursor: "help"},
    url: {color: "#f8f8f2"},
    variable: {color: "#f8f8f2"},
    atrule: {color: "#ff79c6"},
    "attr-value": {color: "#f1fa8c"},
    function: {color: "#50fa7b"},
    "class-name": {color: "#8be9fd"},
    keyword: {color: "#ff79c6"},
    regex: {color: "#ffb86c"},
    important: {color: "#ffb86c", fontWeight: "bold"},
    bold: {fontWeight: "bold"},
    italic: {fontStyle: "italic"},
}

export default darkTheme

