const lightTheme = {
    'code[class*="language-"]': {
        color: "#24292e",
        background: "none",
        textAlign: "left",
        whiteSpace: "pre",
        wordSpacing: "normal",
        wordBreak: "normal",
        wordWrap: "normal",
        lineHeight: "1.5",
        tabSize: "2",
        hyphens: "none",
    },
    'pre[class*="language-"]': {
        color: "#24292e",
        background: "none",
        textAlign: "left",
        whiteSpace: "pre",
        wordSpacing: "normal",
        wordBreak: "normal",
        wordWrap: "normal",
        lineHeight: "1.5",
        tabSize: "2",
        hyphens: "none",
        padding: "1em",
        margin: "0",
        overflow: "auto",
        borderRadius: "0.3em",
    },
    ':not(pre) > code[class*="language-"]': {
        background: "none",
        padding: ".1em",
        borderRadius: ".3em",
        whiteSpace: "normal",
    },
    comment: {color: "#6a737d"},
    prolog: {color: "#6a737d"},
    doctype: {color: "#6a737d"},
    cdata: {color: "#6a737d"},
    punctuation: {color: "#24292e"},
    property: {color: "#d73a49"},
    tag: {color: "#d73a49"},
    constant: {color: "#6f42c1"},
    symbol: {color: "#6f42c1"},
    deleted: {color: "#6f42c1"},
    boolean: {color: "#6f42c1"},
    number: {color: "#6f42c1"},
    selector: {color: "#22863a"},
    "attr-name": {color: "#22863a"},
    string: {color: "#032f62"},
    char: {color: "#032f62"},
    builtin: {color: "#032f62"},
    inserted: {color: "#032f62"},
    operator: {color: "#d73a49"},
    entity: {color: "#24292e", cursor: "help"},
    url: {color: "#24292e"},
    variable: {color: "#24292e"},
    atrule: {color: "#d73a49"},
    "attr-value": {color: "#032f62"},
    function: {color: "#6f42c1"},
    "class-name": {color: "#005cc5"},
    keyword: {color: "#d73a49"},
    regex: {color: "#e36209"},
    important: {color: "#e36209", fontWeight: "bold"},
    bold: {fontWeight: "bold"},
    italic: {fontStyle: "italic"},
}

export default lightTheme

