-- +goose Up
CREATE TABLE IF NOT EXISTS email_template
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code             VARCHAR(80)  NOT NULL,
    name             VARCHAR(120) NOT NULL,
    event_name       VARCHAR(120) NOT NULL,
    subject_template TEXT         NOT NULL,
    html_template    TEXT         NOT NULL DEFAULT '',
    text_template    TEXT         NOT NULL DEFAULT '',
    to_emails        JSONB        NOT NULL DEFAULT '[]'::jsonb,
    is_enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  DEFAULT now(),
    updated_at       TIMESTAMPTZ  DEFAULT now(),
    deleted_at       TIMESTAMPTZ,

    CONSTRAINT uq_email_template_code UNIQUE (code),
    CONSTRAINT chk_email_template_to_emails_array CHECK (jsonb_typeof(to_emails) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_email_template_event_enabled
    ON email_template (event_name, is_enabled)
    WHERE deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS email_outbox
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id   BIGINT,
    template_code VARCHAR(80)  NOT NULL,
    event_name    VARCHAR(120) NOT NULL,
    to_emails     JSONB        NOT NULL DEFAULT '[]'::jsonb,
    subject       TEXT         NOT NULL,
    html_body     TEXT         NOT NULL,
    text_body     TEXT         NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'pending',
    retry_count   INT          NOT NULL DEFAULT 0,
    next_retry_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    last_error    TEXT,
    sent_at       TIMESTAMPTZ,
    created_at    TIMESTAMPTZ  DEFAULT now(),
    updated_at    TIMESTAMPTZ  DEFAULT now(),

    CONSTRAINT fk_email_outbox_template_id FOREIGN KEY (template_id)
        REFERENCES email_template (id) ON DELETE SET NULL,
    CONSTRAINT chk_email_outbox_status
        CHECK (status IN ('pending', 'sending', 'sent', 'failed')),
    CONSTRAINT chk_email_outbox_to_emails_array CHECK (jsonb_typeof(to_emails) = 'array')
);

CREATE INDEX IF NOT EXISTS idx_email_outbox_status_retry
    ON email_outbox (status, next_retry_at);

CREATE INDEX IF NOT EXISTS idx_email_outbox_created_at
    ON email_outbox (created_at DESC);

CREATE TABLE IF NOT EXISTS email_subscription
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255) NOT NULL,
    event_name      VARCHAR(120) NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'active',
    token           VARCHAR(80)  NOT NULL,
    source_ip       VARCHAR(45),
    unsubscribed_at TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  DEFAULT now(),
    updated_at      TIMESTAMPTZ  DEFAULT now(),

    CONSTRAINT uq_email_subscription_email_event UNIQUE (email, event_name),
    CONSTRAINT uq_email_subscription_token UNIQUE (token),
    CONSTRAINT chk_email_subscription_status
        CHECK (status IN ('active', 'unsubscribed', 'blocked'))
);

CREATE INDEX IF NOT EXISTS idx_email_subscription_event_status
    ON email_subscription (event_name, status);

CREATE INDEX IF NOT EXISTS idx_email_subscription_updated_at
    ON email_subscription (updated_at DESC);

INSERT INTO sys_config (config_key, value)
VALUES ('email.enabled', 'false'),
       ('email.from.address', ''),
       ('email.from.name', ''),
       ('email.defaultTo', ''),
       ('email.smtp.host', ''),
       ('email.smtp.port', '587'),
       ('email.smtp.username', ''),
       ('email.smtp.password', ''),
       ('email.smtp.tlsMode', 'starttls'),
       ('email.send.timeoutSeconds', '10'),
       ('email.send.workers', '2'),
       ('email.send.queueSize', '200'),
       ('email.send.maxRetries', '3'),
       ('email.subscription.blockedIPs', '')
ON CONFLICT (config_key) DO NOTHING;

UPDATE sys_config
SET group_path  = 'notification/email',
    label       = '启用邮件',
    description = '启用后系统将按事件异步发送邮件',
    value_type  = 'bool',
    sort        = 10,
    meta        = '{"inputType":"switch"}'::jsonb
WHERE config_key = 'email.enabled';

UPDATE sys_config
SET group_path   = 'notification/email',
    label        = '发件邮箱',
    description  = 'SMTP 发件地址',
    value_type   = 'string',
    sort         = 20,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb
WHERE config_key = 'email.from.address';

UPDATE sys_config
SET group_path   = 'notification/email',
    label        = '发件人名称',
    description  = '邮件展示名，可选',
    value_type   = 'string',
    sort         = 30,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb
WHERE config_key = 'email.from.name';

UPDATE sys_config
SET group_path   = 'notification/email',
    label        = '默认收件人',
    description  = '逗号分隔，模板未配置收件人时使用',
    value_type   = 'string',
    sort         = 40,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb,
    meta         = '{"placeholder":"admin@example.com,ops@example.com"}'::jsonb
WHERE config_key = 'email.defaultTo';

UPDATE sys_config
SET group_path   = 'notification/email/smtp',
    label        = 'SMTP Host',
    value_type   = 'string',
    sort         = 10,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb
WHERE config_key = 'email.smtp.host';

UPDATE sys_config
SET group_path   = 'notification/email/smtp',
    label        = 'SMTP Port',
    value_type   = 'number',
    sort         = 20,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb
WHERE config_key = 'email.smtp.port';

UPDATE sys_config
SET group_path   = 'notification/email/smtp',
    label        = 'SMTP 用户名',
    value_type   = 'string',
    sort         = 30,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb
WHERE config_key = 'email.smtp.username';

UPDATE sys_config
SET group_path   = 'notification/email/smtp',
    label        = 'SMTP 密码',
    value_type   = 'string',
    is_sensitive = TRUE,
    sort         = 40,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb,
    meta         = '{"inputType":"password"}'::jsonb
WHERE config_key = 'email.smtp.password';

UPDATE sys_config
SET group_path   = 'notification/email/smtp',
    label        = 'TLS 模式',
    value_type   = 'enum',
    enum_options = '[{"label":"不使用 TLS","value":"none"},{"label":"STARTTLS","value":"starttls"},{"label":"TLS(465)","value":"tls"}]'::jsonb,
    sort         = 50,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb
WHERE config_key = 'email.smtp.tlsMode';

UPDATE sys_config
SET group_path   = 'notification/email/send',
    label        = '发送超时(秒)',
    value_type   = 'number',
    sort         = 10,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb,
    meta         = '{"unit":"s"}'::jsonb
WHERE config_key = 'email.send.timeoutSeconds';

UPDATE sys_config
SET group_path   = 'notification/email/send',
    label        = 'Worker 并发数',
    value_type   = 'number',
    sort         = 20,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb
WHERE config_key = 'email.send.workers';

UPDATE sys_config
SET group_path   = 'notification/email/send',
    label        = '发送队列长度',
    value_type   = 'number',
    sort         = 30,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb
WHERE config_key = 'email.send.queueSize';

UPDATE sys_config
SET group_path   = 'notification/email/send',
    label        = '失败重试次数',
    value_type   = 'number',
    sort         = 40,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb
WHERE config_key = 'email.send.maxRetries';

UPDATE sys_config
SET group_path   = 'notification/email/subscription',
    label        = '订阅 IP 黑名单',
    description  = '逗号分隔，命中后禁止订阅/退订接口访问',
    value_type   = 'string',
    sort         = 10,
    visible_when = '[{"key":"email.enabled","op":"eq","value":true}]'::jsonb,
    meta         = '{"placeholder":"1.2.3.4,5.6.7.8"}'::jsonb
WHERE config_key = 'email.subscription.blockedIPs';

INSERT INTO email_template (code,
                            name,
                            event_name,
                            subject_template,
                            html_template,
                            text_template,
                            to_emails,
                            is_enabled)
VALUES ('article.published.notify',
        '文章更新推送邮件',
        'article.published',
        '[博客更新] {{.Title}}',
        '<!doctype html><html><body><h2>文章更新：{{.Title}}</h2><p>有一篇新文章已发布。</p><p>访问链接：<a href="{{.public_url}}/articles/short/{{.ShortURL}}">{{.public_url}}/articles/short/{{.ShortURL}}</a></p><p style="color:#666;">事件：{{.eventName}} | 时间：{{.occurredAt}}</p></body></html>',
        '文章更新：{{.Title}}\n\n访问链接：{{.public_url}}/posts/{{.ShortURL}}\n\n事件：{{.eventName}}\n时间：{{.occurredAt}}',
        '[]'::jsonb,
        TRUE),
       ('comment.created.notify',
        '评论创建通知邮件',
        'comment.created',
        '[新评论] {{.NickName}} 在评论区 {{.AreaID}} 发表了评论',
        '<!doctype html><html><body><h2>收到新评论</h2><p><strong>{{.NickName}}</strong> 刚刚提交了一条评论：</p><blockquote style="margin:12px 0;padding:8px 12px;border-left:3px solid #ddd;">{{.Content}}</blockquote><p>评论区 ID：{{.AreaID}}</p><p>状态：{{.Status}}</p><p style="color:#666;">事件：{{.eventName}} | 时间：{{.occurredAt}}</p></body></html>',
        '收到新评论\n\n评论人：{{.NickName}}\n评论区 ID：{{.AreaID}}\n状态：{{.Status}}\n内容：\n{{.Content}}\n\n事件：{{.eventName}}\n时间：{{.occurredAt}}',
        '[]'::jsonb,
        TRUE)
ON CONFLICT (code) DO NOTHING;

UPDATE email_template
SET subject_template = '[博客更新] {{.Title}}',
    html_template    = '<!doctype html><html><body><h2>文章更新：{{.Title}}</h2><p>有一篇新文章已发布。</p><p>访问链接：<a href="{{.public_url}}/articles/short/{{.ShortURL}}">{{.public_url}}/articles/short/{{.ShortURL}}</a></p><p style="color:#666;">事件：{{.eventName}} | 时间：{{.occurredAt}}</p></body></html>',
    text_template    = '文章更新：{{.Title}}\n\n访问链接：{{.public_url}}/articles/short/{{.ShortURL}}\n\n事件：{{.eventName}}\n时间：{{.occurredAt}}'
WHERE code = 'article.published.notify';

-- +goose Down
DELETE
FROM email_template
WHERE code IN ('article.published.notify', 'comment.created.notify');

DELETE
FROM sys_config
WHERE config_key IN ('email.enabled',
                     'email.from.address',
                     'email.from.name',
                     'email.defaultTo',
                     'email.smtp.host',
                     'email.smtp.port',
                     'email.smtp.username',
                     'email.smtp.password',
                     'email.smtp.tlsMode',
                     'email.send.timeoutSeconds',
                     'email.send.workers',
                     'email.send.queueSize',
                     'email.send.maxRetries',
                     'email.subscription.blockedIPs');

DROP INDEX IF EXISTS idx_email_subscription_updated_at;
DROP INDEX IF EXISTS idx_email_subscription_event_status;
DROP TABLE IF EXISTS email_subscription;

DROP INDEX IF EXISTS idx_email_outbox_created_at;
DROP INDEX IF EXISTS idx_email_outbox_status_retry;
DROP TABLE IF EXISTS email_outbox;

DROP INDEX IF EXISTS idx_email_template_event_enabled;
DROP TABLE IF EXISTS email_template;
